### ISSUE TITLE
Error during redisplay: (jit-lock-function 327) signaled (invalid-function (svg-tag-make "FOO"))

### ISSUE THREAD

**Issue by aaronjensen** [rougier/svg-tag-mode#16]
On Emacs 29, I get an error when I try and use any tag configuration that includes a function invocation with arguments:

```el
(setq svg-tag-tags
        '(("TODO" . ((svg-tag-make "FOO")))
        ("DONE" . (svg-tag-make))))
```

The `DONE` one works, but I can't get the other one to work.

I can work around it by using lambda:

```el
(setq svg-tag-tags
        '(("TODO" . ((lambda (_) (svg-tag-make "FOO"))))
        ("DONE" . (svg-tag-make))))
```

**Comment by aaronjensen** [comment]
I just saw your reddit comment, maybe it's just the README that's wrong and this should not work?

**Comment by rougier** [comment]
Thanks. README  has just been corrected.
