### ISSUE TITLE
Some suggestion

### ISSUE THREAD

**Issue by tsuu32** [rougier/svg-tag-mode#2]
Hi,
thanks for this very nice package!
Using SVG makes Emacs more elegant😍

I tried example.el and found some suggestions.

1. `svg-tag-mode.el` should have `(require 'subr-x)` because of `string-trim`.
2. Why making 2 rectangles?  `:stroke` and `:stroke-width`can be used for just 1 rectangle. (or you think this is less elegant?)

Thanks.

**Comment by rougier** [comment]
Thanks.

1. I just forgot. Can you make a PR?
2. Exactly. I tried with the stroke and the rendering was far from satisfying (too heavy in the corners) and ended up with the double rectangle.
