### ISSUE TITLE
Major modes where svg-tag-mode works

### ISSUE THREAD

**Issue by proudot** [rougier/svg-tag-mode#23]
Hi there, svg-tag-mode works in *.el and *.org but not in *.txt for example. Any reasons for that ? 

Cheers!

**Comment by rougier** [comment]
svg-tag-mode relies on font-lock-mode being activated to insert its own keyword. Try activating font-lock mode and it should work. Maybe it's worth a mention in the README.

**Comment by proudot** [comment]
Yes, it solves the issue ! Thanks :).
