### ISSUE TITLE
SVG On/Off showing on new buffers

### ISSUE THREAD

**Issue by howardabrams** [rougier/svg-tag-mode#29]
Minor nit, but whenever a buffer is loaded, the mode message that SVG is on/off is displayed. While innocuous, I have a program that loads a file and displays a message from a hydra, and the message is overridden. 

Most minor modes don't send such a message, so could we remove it? I'll send a PR.

**Comment by rougier** [comment]
Yes, it was originally for debug purpose and the message is not really useful anymore.
