### ISSUE TITLE
Enhancement : implement `org-appear` or `org-fragtog` like functionality

### ISSUE THREAD

**Issue by deb75** [rougier/svg-tag-mode#31]
Hi,

First, thanks for bringing svgs to `org-mode`, I think it opens endless opportunities to make org
files look nicer.

However, it is sometimes practical to see the real text, the one you see when you open org files
with another editor.

As an example, schedules are prettified by `svg-tag-mode`, I checked that you can modify the
schedule when cursor is above svg, this latter is instantly updated after having modified the
schedule.

However, you cannot see directly the modification. For that, one should disable `svg-tag-mode`
and re-enable it after. But it is more practical to modify the text when you clearly see it.

To do this, would it be possible to implement an `org-appear` or `org-fragtog` like functionality.
You probably already know these packages, the idea of second one is to make equations appear
as text as soon as cursor is within the latex fragment and, display the svg equation otherwise.

Then, `svg-tag-mode` should replace text by svgs wherever it has to, except when cursor is within
one element (date, priority, tag, ...)

Regards

**Comment by rougier** [comment]
Did you try `(setq svg-tag-action-at-point 'edit)`, does that answer your question or you have something different in mind?

**Comment by deb75** [comment]
That is exactly what I was expecting, sorry, I did not know it was already implemented.

Regards
