### ISSUE TITLE
Provide configuration for multiple tags

### ISSUE THREAD

**Issue by KChousos** [rougier/svg-tag-mode#33]
First of all, thanks for this very useful package.
Since I'm not well versed with regexp, I'm trying to find a way for svg-tag-mode to render correctly multiple tags side by side, e.g. `:foo:bar:`. I couldn't figure anything out using the examples.

Thanks again for all your hard work!

**Comment by rougier** [comment]
Have a look at https://github.com/rougier/svg-tag-mode/issues/20, I think this is the best we can do  because emacs does not have look-ahead expression in regex and this would make our life easier.

**Comment by rougier** [comment]
Did the provided approach worked?

**Comment by KChousos** [comment]
Closed it since I can't test for now the package, due to another issue I posted (as of now, only progress bars work on my config). It might have to do with the fact I'm using emacs 29.

**Comment by rougier** [comment]
Ok. I replied on your other issue to try to debug the problem.
