### ISSUE TITLE
How to change SVG Colors

### ISSUE THREAD

**Issue by ragreenburg** [rougier/svg-tag-mode#35]
In the screenshots in the README, there are different colors for TODO, MEETING, and DONE. I was curious how one can set the color of their SVG's?

**Comment by deb75** [comment]
Hello,

I have a similar question.

I would like to change the background color of some svgs.

I defined a new face : 
```elisp
(defface svg-tag-todo '((t (:inherit org-todo) :height 0.5 :background "red"))
  "Face for todo")
```
with a red background color and, I added : 
```elisp
        ("^[\\*]+[\s-]+\\(TODO\\)[\s-]+" . ((lambda (tag) (svg-tag-make tag :face 'svg-tag-todo :inverse t :margin 0))))
```
to the list of  `svg-tag-tags`.

It did change the background color, but not in red.

**Comment by rougier** [comment]
It's actually a design choice as written in the documentation:
```lisp
(defun svg-tag-make (tag &optional &rest args)
  "Return a svg tag displaying TAG and using specified ARGS.
   
  ARGS are passed to the `svg-lib-tag' function but there are
  supplementary arguments:
  :beg (integer) specifies the first index of the tag substring to
                 take into account (default 0)
  :end (integer) specifies the last index of the tag substring to
                 take into account (default nil)
  :face (face) indicates the face to use to compute foreground &
               background color (default 'default)
  :inverse (bool) indicates whether to inverse foreground &
                  background color (default nil)
   Note that :foreground, :background, :stroke and :font-weight
   cannot be specified because thay are overwritten by the
   function. If you need full control of tag appearance, best is
   to call svg-lib-tag directly."
```

If you need full control of each property, then you can use the `svg-lib-tag` method.

**Comment by deb75** [comment]
Hi,

Thanks for your answer.

My understanding is that if I define a face with a color background and put this face as argument of `svg-tag-make`,
then this one shoudl use it. Am I right ?

Then, what is strange for me is that if I define a face : 
```elisp
(defface myface '((t (:inherit org-todo) :height 0.5 :background "#FF0000")) "Face for todo")
```
and if I try to retrieve the backgroudn color of this face : 
```elisp
(face-background 'myface nil 'default)
```
I get `#FDF6E3`. Shouldn't I get `#FF0000` ?

**Comment by rougier** [comment]
I think it should be `(defface myface '((t (:inherit org-todo  :height 0.5  :background "#FF0000"))) "Face for todo")`

**Comment by deb75** [comment]
Yes, I figured it out by searching how to define faces.

Now, it works, except that because of `inverse t`, one has to modify the `foreground` color of face for the svg background color to be effectively changed.

Regards
