### ISSUE TITLE
Need mechanism to adjust layout?

### ISSUE THREAD

**Issue by MetroWind** [rougier/svg-tag-mode#4]
I guess it's probably the font metrics, but on my end it looks like this :->
![partial-2020-10-17T12:49:28](https://user-images.githubusercontent.com/9159/96352415-cfe55d00-1077-11eb-88e0-45f1042b7976.png)
Still, I'm surprised it'd be off by this much.

The font I'm using is [Rec Mono Duotone](https://github.com/arrowtype/recursive) @11px.

**Comment by progfolio** [comment]
Similar issue on my end, though I don't even get the clipped text.

**Comment by rougier** [comment]
Oh weird. Can you play with the text-y variable (for example using `(+ text-y 10)`or `(- text-y 10)` ?

**Comment by MetroWind** [comment]
Yeah, I subtracted `text-y` by 10 in `svg-tag-make` and it was fine. I guess one way to do this is to add a customizable `text-vertical-offset`, or figure out a way to calculate it correctly, which might be hard; fonts are weird...

**Comment by rougier** [comment]
Thanks, I'll add offset option.

**Comment by rougier** [comment]
Done.

**Comment by yousufinternet** [comment]
Hi, 
I can't find the right keyword to use for offsetting the text, also is it possible to offset it horizontally? 
Thanks

**Comment by rougier** [comment]
Can you open a new issue, this one is closed.
