### ISSUE TITLE
left mouse clicks on svg tags not working as expected (doom emacs / org-mode)

### ISSUE THREAD

**Issue by wolfangpauli** [rougier/svg-tag-mode#41]
I' m on Doom emacs/org-mode and have the issue that a left-button mouse click on an svg-tags does not work like I would expect it.

Hovering over the tag -> ok, left mouse click on links -> ok, but when I left-click on the svg-tag nothing happens.
I can select the tag by the left mouse click but have to subsequently press 'enter' in order to call a function (e.g. get the buffer evaluated like in notebook-mode)

Is "left click + enter" the required action or should just a left-button mouse click on the svg-tag be sufficient in order to call a specified function.

Unfortunately, I do not know if it's just my misunderstanding, an svg-tag-mode issue or Doom emacs related.

Thanks for your excellent work on svg-tag-mode and for help or a clue in advance.

**Comment by rougier** [comment]
Would you have a minimal org-file showing the problem in order to test it on my side?

**Comment by wolfangpauli** [comment]
I used the notebook.org file from your notebook-mode (https://github.com/rougier/notebook-mode).
Since I consider this issue rather (if at all) as svg-tag related I did post it as an issue of notebook-mode.

Thx for your help!

**Comment by rougier** [comment]
Can you try to evaluate this and then click on TEST?
```
(require 'svg-tag-mode)
(defun test() (messge "click"))

(setq svg-tag-tags
      '(("^;; TEST" .     ((lambda (tag) (svg-tag-make "TEST"))
                          'test-click "Call function"))))
(font-lock-mode)
(svg-tag-mode)

;; TEST
```

**Comment by wolfangpauli** [comment]
Thank you! Your example does not work for me even when changing 'test-click -> 'test
But in one of your files I found a hint leading me to try the following code that actually works for me.

(require 'svg-tag-mode)

(defun test() (message "click"))


(setq svg-tag-tags
      '(("^;; TEXT" .     ((lambda (tag) (svg-tag-make "TEXT"))
                          (lambda () (interactive)(test)) "Call function"))))



(font-lock-mode)
(svg-tag-mode)

;; TEXT

**Comment by rougier** [comment]
We're making progress! Not too sure why the interactive is needed. I inserted in the example file when a tag can be clicked but I don't remember the exact reason. Does this solve you problem then (by adding interactive)?

P.S.: I edited your comment to format code (by adding ` ```emacs-lisp ` before and ` ``` ` after.

**Comment by wolfangpauli** [comment]
I replaced the corresponding code parts in a local version of notebook.el (for notebook-mode) and it works like a charm ;-)
Yes, (interactive) is the clue to the above mentioned problem.
