### ISSUE TITLE
Does not work if tree-sitter is enabled

### ISSUE THREAD

**Issue by konrad1977** [rougier/svg-tag-mode#42]
I dunno if this bug belongs here or at the tree-sitter repo.
But tree-sitter stops svg-tag-mode from working, if I disable tree-sitter it works for me. Dunno if it _**swift**_ specific or not.

Last week I could use both at the same time without any problems.

**Comment by rougier** [comment]
svg-tag-mode use only regular expression. If you have tree sitter, I guess it would need to use tree-sitter machinery instead. But I'm not familiar enough (yet) with tree-sitter to propose a solution right now.

**Comment by konrad1977** [comment]
Found out when it doesnt work:
`(setq tree-sitter-hl-use-font-lock-keywords t)` must be enabled.
