### ISSUE TITLE
Question: How to enable in minibuffer?

### ISSUE THREAD

**Issue by tam5** [rougier/svg-tag-mode#43]
Has anyone succeeded to enable this mode in the minibuffer? Even when I turn on the global mode I'm not seeing tags rendered in the minibuffer.

Any help would be appreciated, thanks!

**Comment by rougier** [comment]
Tag mode relies on font-lock and the minibuffer does not enforce font-lock. If you want to insert a svg-tag in the modeline, you'll have to do it explicitly:
```
(setq-local mode-line-format (propertize "TAG" 'display (svg-lib-tag "TAG")))
```

**Comment by tam5** [comment]
I understand it now, thanks!

**Comment by chookity-pokk** [comment]
To kind of piggy-back off of this, how can you change the background of the tag? I tried the below snippet, but I get the error, `svg-lib-tag: Wrong type argument: listp, :background`.


`(setq-local mode-line-format (propertize "TAG" 'display (svg-lib-tag "TAG" :background "blue")))`
