### ISSUE TITLE
Change font family with svg-tag-default-face

### ISSUE THREAD

**Issue by konrad1977** [rougier/svg-tag-mode#44]
I tried to set the font, but nothing changes. What's the correct way of doing this?
I am using use-package.

**Comment by ronisbr** [comment]
I had this problem very recently. The font was the cause of my problem here:

I solved if by customizing the variable `svg-lib-style-default`:

```
(use-package! svg-tag-mode
  :config
  (plist-put svg-lib-style-default :font-family "JetBrainsMono Nerd Font")
  (plist-put svg-lib-style-default :font-size 13))
```

**Comment by konrad1977** [comment]
Thanks that worked.
