### ISSUE TITLE
Question: Tags with spaces between characters 

### ISSUE THREAD

**Issue by chookity-pokk** [rougier/svg-tag-mode#45]
Is there a way to configure the regex to allow tags to have spaces between the characters? This would allow a tag with multiple words.

**Comment by rougier** [comment]
I see no difficulty with that. Do you mean you tried and it failed? By the way, you can test your regex with `regexp-builded`

**Comment by chookity-pokk** [comment]
I don't know what was causing the issue but it seems to be gone now. Essentially what was happening was when I would add a regex with multiple words it caused all my tags to disappear. It was likely related to something else in my svg-tag config because it's fixed now. 

Thank you for `regexp-builder`! Didn't know that existed!
