### ISSUE TITLE
Don't hard code the default font family

### ISSUE THREAD

**Issue by progfolio** [rougier/svg-tag-mode#5]
https://github.com/rougier/svg-tag-mode/blob/63d8710d1a742f339d138b83a3ed2630aeb1a28a/svg-tag-mode.el#L76

Could the `:family` be defined programmatically based off of the default face so that it's guaranteed to use a font that the user has installed?

**Comment by rougier** [comment]
Good point. Same for default size that should be 2 point less than the default. Can you make a PR?

**Comment by rougier** [comment]
Just made the change actually.
