### ISSUE TITLE
What is the correct regexp for ~something~ in Org Mode?

### ISSUE THREAD

**Issue by FieryCod** [rougier/svg-tag-mode#8]
I'm trying to create a regexp which would match the following sentences:

1.
```
~sentence-without-space123~
```
2. 
```
~sentence- without-space123~
```

This is definition I have:
```
(setq svg-tags
        '(("\\(\~[0-9a-zA-Z]+\~\\)" 1
           `(face nil display ,(svg-tag-keyboard (match-string 0))))))
```

It seems to me that regex is correct, therefore I'm not quite sure whether it's issue in org-mode or svg-tag. (Or maybe regexp is incorrect)

Anyway I would be highly grateful for any help.

**Comment by rougier** [comment]
In fact, the `\\(` and `\\)` are added automatically. Maybe you could try without them.

**Comment by FieryCod** [comment]
@rougier I tried changing what you suggested without effect. After running some tests I'm pretty sure is that not an issue with regexp nor with the package. I will try to seek for the answer on org mailing list.

Wish you a great day. Thank you for this package!

**Comment by rougier** [comment]
Maybe you can start withe the example file and modifu the ":TODO:" into "~TODO~" and check if ti's working.

**Comment by rougier** [comment]
After second look I think the second part of svg-tags might be wrong. It should be either a svg-tag or a function that build a SVG tag. Again, have a look at [example-1.el](https://github.com/rougier/svg-tag-mode/blob/main/example-1.el)

**Comment by FieryCod** [comment]
~TODO~ does not work. It's definitely org's issue.

**Comment by rougier** [comment]
Oh, if you test it in org mode and if you're hiding markup, org will take precedence and the `~` will "dissapear". It shoudl work in text mode. If you'e using org-mode, make sure to text example-2.el

**Comment by qingbyin** [comment]
Hi, could you post the solution (i.e. correct re) here? I also can not achieve this goal.

**Comment by rougier** [comment]
@qingbyin Did you check example-2.el?
