### ISSUE TITLE
Unable to view SVG images properly

### ISSUE THREAD

**Issue by Compro-Prasad** [rougier/svg-tag-mode#9]
There is a prerequisite which I think I don't have on my machine. Also, I think I don't have proper Unicode support for special characters. Do you know how to enable it? For example, I am not able to display 🚀 character in terminal and in Emacs.

Arch Linux
Emacs 28.0.50
`system-configuration-features` value is `"XPM JPEG TIFF GIF PNG RSVG CAIRO IMAGEMAGICK SOUND GPM DBUS GSETTINGS GLIB NOTIFY INOTIFY ACL GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER LCMS2"`

The issue is described [here](https://github.com/melpa/melpa/pull/7217#issuecomment-727717844).

**Comment by rougier** [comment]
I think you need to compile emacs with svg support but I'm not sure how to do it on arch linux.

**Comment by jsilve24** [comment]
I am running into a similar problem, is the "RSVG" feature not svg support?

**Comment by rougier** [comment]
Yes, rsvg is what you need. Can you open an svg file and see the image in Emacs?
